# DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:attendance_user}
quarkus.datasource.password=${DB_PASSWORD:secret}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:edutrack}

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.mapping.format.global=ignore

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=attendance
quarkus.flyway.default-schema=attendance
quarkus.flyway.create-schemas=true

# OpenAPI
quarkus.smallrye-openapi.info-title=Attendance MS API
quarkus.smallrye-openapi.info-version=1.0.0-SNAPSHOT
quarkus.smallrye-openapi.info-description=EduTrack - Registro y control de asistencia por clase

# Logging
quarkus.log.level=INFO
quarkus.log.category."cl.duocuc.edutrack".level=DEBUG
